# Configuration File
# 
# Author: Dingquan Li
# Email: dingquanli@pku.edu.cn
# Date: 2018/4/18
# 
# f = open('config.yaml')
# conf = yaml.load(f)
# print(conf)  
# f.close()
# conf.update(conf[conf['database']]) #
# conf.update(conf[conf['model']]) #

###################### Base Settings######################
use_cuda: True #
enableTensorboard: False #
test_during_training: False #

database: TID2013 # TID2008 or TID2013?
model: WaDIQaM-FR
TID2013:
  datainfo: data/TID2013fullinfo.mat
  im_dir: /datasets/qa/tid2013/distorted_images/ #/media/ldq/Research/Data/tid2013/distorted_images/ # 
  ref_dir: /datasets/qa/tid2013/reference_images/ # /media/ldq/Research/Data/tid2013/reference_images/ # 
TID2008:
  datainfo: data/TID2008fullinfo.mat
  im_dir: /datasets/qa/tid2008/distorted_images/ # /media/ldq/Research/Data/tid2008/distorted_images/ # 
  ref_dir: /datasets/qa/tid2008/reference_images/ # /media/ldq/Research/Data/tid2008/reference_images/ # 
WaDIQaM-FR:
  type: FR
WaDIQaM-NR:
  type: NR

tw: 32
th: 32
n_patches: 32

train_ratio: 0.6
# val_ratio: 0.2  #
test_ratio: 0.2  #
batch_size: 4
learning_rate: 0.0001
weight_decay: 0
n_epochs: 3000